### ISSUE TITLE
Event source for Cloudwatch event state always Enabled

### ISSUE THREAD

**Issue by madarve** [jorgebastida/gordon#103]
When assigning a CloudWatch event as an event source, the "state" parameter in the settings.yml is ignored, and will always be ENABLED.

How to reproduce:

1. Create an app with an event source mapping such as:
```
events:
  my_event_trigger:
    state: DISABLED
    description: Event to test this bug
    schedule_expression: rate(1 day)
    targets:
      some_app:
        lambda: some_app.some_lambda
```
2. gordon build && gordon apply
3. Go to to the lambda in question, in the Trigger's tab you should see the event source mapped.

Expected Result:
- The event mapping should be in DISABLED state.

Actual Result:
- Event Mapping shows as ENABLED.
