### ISSUE TITLE
Query params not propagated to lambda

### ISSUE THREAD

**Issue by azizmb** [jorgebastida/gordon#117]
I'm trying to set up an apigateway <-> lambda integration, but am struggling with getting a query param passed to the lambda. From the docs and examples, I see I should have something like the following in my lambda:

```
apigateway:
  my-api:
    description: API for layer callbacks
    resources:
      /test:
        methods: [GET, POST]
        parameters:
          method.request.querystring.verification_challenge: True
        integration:
          lambda: myapp.helloworld
          parameters:
            integration.request.querystring.verification_challenge: method.request.querystring.verification_challenge
```

Yet, with this, the query string param (`verification_challege`) does not get propagated to the lambda, and events is an empty dict.

Am I doing something wrong? 

Attached is a sample application to try this: [urlparam.zip](https://github.com/jorgebastida/gordon/files/639358/urlparam.zip)
After applying, 
```
$ curl https://<gateway domain>/dev/test?verification_challenge=asdf
"{}"
```
