### ISSUE TITLE
s3 suffix filter overlap exception

### ISSUE THREAD

**Issue by tjbaker** [jorgebastida/gordon#118]
Using the same key_filter suffix in different notifications throws a suffix filter overlap exception.  Why does it matter if the same suffix is specified in more than one notification?

Exception
`One or more suffix filters overlap one to each other log, log.`

```
s3:

  elb_s3_integration:
    bucket: the_bucket
    notifications:

      prod_elb_on_create:
        lambda: elb.ELBLogs
        events:
          - "s3:ObjectCreated:*"
        key_filters:
          prefix: PROD
          suffix: log

      stg_elb_on_create:
        lambda: elb.ELBLogs
        events:
          - "s3:ObjectCreated:*"
        key_filters:
          prefix: STG
          suffix: log
```
