### ISSUE TITLE
support for binary data in API Gateway

### ISSUE THREAD

**Issue by ahl** [jorgebastida/gordon#132]
See: https://aws.amazon.com/about-aws/whats-new/2016/11/binary-data-now-supported-by-api-gateway/

This would look like a peer to `resources` under an `apigateway` API:

```yaml
apigateway:
  my-api:
    resources:
      ...
    binary_support:
      image/png: True
      image/jpeg: True
      application/octet-stream: True
```
