### ISSUE TITLE
Option to fix lambda name in settings.yml

### ISSUE THREAD

**Issue by trecouvr** [jorgebastida/gordon#137]
It would like the option to fix my lambda names instead of gardon auto-generating it for me.

```
lambdas:
  helloworld:
    name: myAwesomeLambdaName
    runtime: nodejs6.10
    ..
 ```

I managed to hack gordon to pass the setting to troposphere.awslambda.Function and I can make a PR if you are interested.
