### ISSUE TITLE
No trigger from s3:ObjectCreated:*

### ISSUE THREAD

**Issue by bomatson** [jorgebastida/gordon#16]
Hi there! Thanks for creating this awesome tool.

I was trying to test it out by having a lambda function respond to an object being created in an existing S3 bucket `test-bucket`. However, adding a file to that bucket is not triggering the function, nor am I seeing any addition to the event sources for that lambda function in the AWS console. In my project `settings.yml`:

```
---
project: test
default-region: us-east-1
code-bucket: gordon-test-326a588b
apps:
  - gordon.contrib.helpers
  - gordon.contrib.lambdas
  - gordon.contrib.s3
  - scouting_locations

s3:
  scouting_s3_integration:
    bucket: arn:aws:s3:::test-bucket
    notifications:
      on_create:
        lambda: scouting_locations.helloworld
        events:
          - s3:ObjectCreated:*
```

I'm able to test the lambda function successfully in the AWS console, just not when the test bucket changes. Did I miss a step?
