### ISSUE TITLE
Using reference in settings.yml policy fails

### ISSUE THREAD

**Issue by oseibonsu** [jorgebastida/gordon#55]
Using a reference parameter in the following manner results in  `Template format error: Unresolved resource dependencies [arn] in the Resources block of the template`

``` yaml
lambdas:
  get:
    code: get
    handler: code.handler
    runtime: nodejs4.3
    policies:
      example_bucket_policy:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - "dynamodb:GetItem"
            Resource: ref://arn
            Effect: "Allow"
```

There references in defined in the parameter directory in a file call dev.yml

``` yaml

---
secret: secret
table: metaTags-dev
arn: arn:aws:dynamodb:us-east-1:123456789:table/metaTags-dev
```

**Comment by tjsail33** [comment]
@oseibonsu might want to edit your secret out of that.

**Comment by mario-harper-volusion** [comment]
+1

**Comment by tjbaker** [comment]
I ran into a similar issue when trying to use jinja2 syntax within a policy map.

ie.  

```
                -
                    Action:
                        - "lambda:InvokeFunction"
                    Resource: "arn:aws:lambda:{{ region }}:{{ account }}:elblogs"
                    Effect: "Allow"
```

The variable is not expanded and cloudformation fails attempting to create the role.
