### ISSUE TITLE
How to create new S3 event source for diff --stage?

### ISSUE THREAD

**Issue by kienpham2000** [jorgebastida/gordon#88]
Hi guys,

I have my simple s3 event source setting like this at the main `settings.yml` file, to call my lambda when a file is uploaded to a bucket. 

```
s3:
  my_s3_integration:
    bucket: my-s3-bucket
    notifications:
      my_s3_file_uploaded:
        lambda: my_lambda_to_handle_file
        events:
          - s3:ObjectCreated:*
```

Now I want to do 2 diff stage, dev and prod. When I deploy with: `gordon build --stage prod`, it overwrites my S3 bucket event source setting for `dev`. 

How can I have 2 S3 triggers triggering diff lambda based on --stage?

Thanks!
